// Code generated by codex-folio OpenAPI generator 1.0.0; DO NOT EDIT.
// Contract source: api/openapi.json
// Response schemas: ActivityResponse, BootstrapResponse, MetadataResponse, ProjectsResponse, SelectionResponse, UsageSnapshotResponse
package httpapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

const (
	APIVersion           = "v1"
	ActivityPath         = "/api/v1/activity"
	AnalyticsPath        = "/api/v1/analytics"
	HistoryPath          = "/api/v1/analytics/history"
	ContractVersion      = "0.0.1-alpha"
	ContractSourceSHA256 = "ba6d6079ceac206cb4915c4f0f211a7529090ff3837384e5a83f3ce7b19f00de"
	BootstrapPath        = "/api/v1/bootstrap"
	MetadataPath         = "/api/v1/meta"
	ProjectsPath         = "/api/v1/projects"
	SelectionPath        = "/api/v1/selection"
	UsageLatestPath      = "/api/v1/usage/latest"
	UsageRefreshPath     = "/api/v1/usage/refresh"
)

type HistoryScope struct {
	ProfileId string   `json:"profile_id"`
	ProjectId string   `json:"project_id"`
	From      string   `json:"from"`
	To        string   `json:"to"`
	Classes   []string `json:"classes"`
}

type HistoryRequest struct {
	Action       string                  `json:"action"`
	Setting      *string                 `json:"setting,omitempty"`
	Run          *bool                   `json:"run,omitempty"`
	Scope        *HistoryScope           `json:"scope,omitempty"`
	Confirmation *string                 `json:"confirmation,omitempty"`
	Export       *AnalyticsExportRequest `json:"export,omitempty"`
}

type HistoryResponse struct {
	Retention  *RetentionResult       `json:"retention,omitempty"`
	Purge      *PurgeResult           `json:"purge,omitempty"`
	Aggregates *[]HistoryAggregate    `json:"aggregates,omitempty"`
	Export     *AnalyticsExportResult `json:"export,omitempty"`
}

type RetentionResult struct {
	Setting   string `json:"setting"`
	Processed int64  `json:"processed"`
	More      bool   `json:"more"`
}

type PurgeResult struct {
	Scope        HistoryScope         `json:"scope"`
	Counts       []HistoryRecordCount `json:"counts"`
	Confirmation string               `json:"confirmation"`
	RecordLimit  int64                `json:"record_limit"`
	Executable   bool                 `json:"executable"`
	Applied      bool                 `json:"applied"`
}

type HistoryRecordCount struct {
	RecordClass string `json:"record_class"`
	Count       int64  `json:"count"`
}

type HistoryMetric struct {
	MetricKey   string `json:"metric_key"`
	ValueKind   string `json:"value_kind"`
	Unit        string `json:"unit"`
	SourceClass string `json:"source_class"`
	Scope       string `json:"scope"`
	Aggregation string `json:"aggregation"`
}

type HistoryAggregate struct {
	Id              string        `json:"id"`
	ProfileId       string        `json:"profile_id"`
	ProjectId       string        `json:"project_id"`
	Metric          HistoryMetric `json:"metric"`
	Value           float64       `json:"value"`
	Source          string        `json:"source"`
	SourceVersion   string        `json:"source_version"`
	Provenance      string        `json:"provenance"`
	Availability    string        `json:"availability"`
	Assumptions     string        `json:"assumptions"`
	Uncertainty     string        `json:"uncertainty"`
	BucketKind      string        `json:"bucket_kind"`
	BucketStart     string        `json:"bucket_start"`
	BucketEnd       string        `json:"bucket_end"`
	Timezone        string        `json:"timezone"`
	FirstObservedAt string        `json:"first_observed_at"`
	LastObservedAt  string        `json:"last_observed_at"`
	FirstCapturedAt string        `json:"first_captured_at"`
	LastCapturedAt  string        `json:"last_captured_at"`
	Samples         int64         `json:"samples"`
	ProfileAlias    *string       `json:"profile_alias,omitempty"`
	ProjectAlias    *string       `json:"project_alias,omitempty"`
	ProjectBasename *string       `json:"project_basename,omitempty"`
	LoginIdentity   *string       `json:"login_identity,omitempty"`
	Workspace       *string       `json:"workspace,omitempty"`
	Freshness       *string       `json:"freshness,omitempty"`
	CanonicalPath   *string       `json:"canonical_path,omitempty"`
}

type AnalyticsExportRequest struct {
	Format       string   `json:"format"`
	Datasets     []string `json:"datasets"`
	Scope        string   `json:"scope"`
	ProfileId    string   `json:"profile_id"`
	ProjectId    string   `json:"project_id"`
	From         string   `json:"from"`
	To           string   `json:"to"`
	IncludePaths bool     `json:"include_paths"`
}

type AnalyticsExportDatasetPreview struct {
	Dataset     string   `json:"dataset"`
	Fields      []string `json:"fields"`
	RecordCount int64    `json:"record_count"`
}

type UsageExportRecord struct {
	ObservationId     string        `json:"observation_id"`
	ProfileId         string        `json:"profile_id"`
	ProfileAlias      string        `json:"profile_alias"`
	ProjectId         string        `json:"project_id"`
	ProjectAlias      string        `json:"project_alias"`
	ProjectBasename   string        `json:"project_basename"`
	Metric            HistoryMetric `json:"metric"`
	Value             float64       `json:"value"`
	Source            string        `json:"source"`
	SourceVersion     string        `json:"source_version"`
	Provenance        string        `json:"provenance"`
	Freshness         string        `json:"freshness"`
	Availability      string        `json:"availability"`
	LoginIdentity     string        `json:"login_identity"`
	Workspace         string        `json:"workspace"`
	WindowStart       string        `json:"window_start"`
	WindowEnd         string        `json:"window_end"`
	WindowTimezone    string        `json:"window_timezone"`
	ObservedAt        string        `json:"observed_at"`
	CapturedAt        string        `json:"captured_at"`
	CaptureAgeSeconds int64         `json:"capture_age_seconds"`
	Assumptions       string        `json:"assumptions"`
	Uncertainty       string        `json:"uncertainty"`
	CanonicalPath     *string       `json:"canonical_path,omitempty"`
}

type AvailabilityExportRecord struct {
	MetricAvailabilityId string        `json:"metric_availability_id"`
	ProfileId            string        `json:"profile_id"`
	ProfileAlias         string        `json:"profile_alias"`
	ProjectId            string        `json:"project_id"`
	ProjectAlias         string        `json:"project_alias"`
	ProjectBasename      string        `json:"project_basename"`
	Metric               HistoryMetric `json:"metric"`
	State                string        `json:"state"`
	Reason               string        `json:"reason"`
	CheckedAt            string        `json:"checked_at"`
	Source               string        `json:"source"`
	SourceVersion        string        `json:"source_version"`
	Provenance           string        `json:"provenance"`
	Freshness            string        `json:"freshness"`
	CaptureAgeSeconds    int64         `json:"capture_age_seconds"`
	LoginIdentity        string        `json:"login_identity"`
	Workspace            string        `json:"workspace"`
	CanonicalPath        *string       `json:"canonical_path,omitempty"`
}

type AnalyticsExportRecords struct {
	Usage        *[]UsageExportRecord        `json:"usage,omitempty"`
	Availability *[]AvailabilityExportRecord `json:"availability,omitempty"`
	Aggregates   *[]HistoryAggregate         `json:"aggregates,omitempty"`
	Activity     *[]ActivityExportRecord     `json:"activity,omitempty"`
}

type AnalyticsExportResult struct {
	SchemaVersion string                          `json:"schema_version"`
	Filters       AnalyticsExportRequest          `json:"filters"`
	Preview       []AnalyticsExportDatasetPreview `json:"preview"`
	Records       AnalyticsExportRecords          `json:"records"`
}

type ActivityExportRecord struct {
	RecordType      string              `json:"record_type"`
	Id              string              `json:"id"`
	SourceSessionId *string             `json:"source_session_id,omitempty"`
	ProfileId       string              `json:"profile_id"`
	ProfileAlias    string              `json:"profile_alias"`
	ProjectId       *string             `json:"project_id,omitempty"`
	ProjectAlias    *string             `json:"project_alias,omitempty"`
	ProjectBasename *string             `json:"project_basename,omitempty"`
	Source          string              `json:"source"`
	SourceVersion   *string             `json:"source_version,omitempty"`
	Provenance      string              `json:"provenance"`
	StartedAt       string              `json:"started_at"`
	LastObservedAt  string              `json:"last_observed_at"`
	Lifecycle       *string             `json:"lifecycle,omitempty"`
	ExitStatus      *int64              `json:"exit_status,omitempty"`
	Model           *string             `json:"model,omitempty"`
	TokensUsed      *int64              `json:"tokens_used,omitempty"`
	Correlation     ActivityCorrelation `json:"correlation"`
	CanonicalPath   *string             `json:"canonical_path,omitempty"`
}

type ActivityCorrelation struct {
	State           string  `json:"state"`
	ManagedLaunchId *string `json:"managed_launch_id,omitempty"`
	EvidenceType    *string `json:"evidence_type,omitempty"`
	Confidence      *string `json:"confidence,omitempty"`
}

type ActivityRecord struct {
	RecordType                 string  `json:"record_type"`
	Id                         string  `json:"id"`
	SourceSessionId            string  `json:"source_session_id"`
	ProfileId                  string  `json:"profile_id"`
	ProfileAlias               string  `json:"profile_alias"`
	ProjectId                  string  `json:"project_id"`
	ProjectAlias               string  `json:"project_alias"`
	ProjectBasename            string  `json:"project_basename"`
	Source                     string  `json:"source"`
	SourceVersion              string  `json:"source_version"`
	Provenance                 string  `json:"provenance"`
	StartedAt                  string  `json:"started_at"`
	LastObservedAt             string  `json:"last_observed_at"`
	Lifecycle                  string  `json:"lifecycle"`
	ExitStatus                 string  `json:"exit_status"`
	Model                      string  `json:"model"`
	TokensUsed                 string  `json:"tokens_used"`
	CorrelationState           string  `json:"correlation_state"`
	CorrelationManagedLaunchId string  `json:"correlation_managed_launch_id"`
	CorrelationEvidenceType    string  `json:"correlation_evidence_type"`
	CorrelationConfidence      string  `json:"correlation_confidence"`
	CanonicalPath              *string `json:"canonical_path,omitempty"`
}

type ActivityResponse struct {
	Records []ActivityRecord `json:"records"`
}

type AnalyticsResponse struct {
	Scope                string                  `json:"scope"`
	EligibleProfileCount int64                   `json:"eligible_profile_count"`
	RecommendedProfileId string                  `json:"recommended_profile_id"`
	Candidates           []UsageCandidate        `json:"candidates"`
	Profiles             []UsageSnapshotResponse `json:"profiles"`
	Aggregates           []UsageAggregate        `json:"aggregates"`
	Ambiguities          []UsageMetricAmbiguity  `json:"ambiguities"`
	Activity             []ActivityRecord        `json:"activity"`
	Recent               []UsageSnapshotResponse `json:"recent"`
}

type BootstrapRequest struct {
	BootstrapToken string `json:"bootstrap_token"`
}

type BootstrapResponse struct {
	CSRFToken string `json:"csrf_token"`
}

type MetadataResponse struct {
	APIVersion      string `json:"api_version"`
	ContractVersion string `json:"contract_version"`
	Product         string `json:"product"`
}

type ProjectIdentity struct {
	ProjectId string `json:"project_id"`
	Alias     string `json:"alias"`
	Basename  string `json:"basename"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type ProjectsResponse struct {
	Projects []ProjectIdentity `json:"projects"`
}

type SelectionRequest struct {
	Alias string `json:"alias"`
}

type SelectionResponse struct {
	ProfileId   string `json:"profile_id"`
	Alias       string `json:"alias"`
	DisplayName string `json:"display_name"`
	Warning     string `json:"warning"`
}

type UsageRefreshRequest struct {
	Alias         string  `json:"alias"`
	TriggerReason *string `json:"trigger_reason,omitempty"`
}

type UsageErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UsageObservation struct {
	ObservationId     string  `json:"observation_id"`
	MetricKey         string  `json:"metric_key"`
	Value             float64 `json:"value"`
	Unit              string  `json:"unit"`
	ValueKind         string  `json:"value_kind"`
	SourceClass       string  `json:"source_class"`
	Scope             string  `json:"scope"`
	Aggregation       string  `json:"aggregation"`
	ObservedAt        string  `json:"observed_at"`
	CapturedAt        string  `json:"captured_at"`
	CaptureAgeSeconds int64   `json:"capture_age_seconds"`
	WindowStart       string  `json:"window_start"`
	WindowEnd         string  `json:"window_end"`
	WindowTimezone    string  `json:"window_timezone"`
	Source            string  `json:"source"`
	SourceVersion     string  `json:"source_version"`
	Provenance        string  `json:"provenance"`
	Freshness         string  `json:"freshness"`
	Availability      string  `json:"availability"`
	Assumptions       string  `json:"assumptions"`
	Uncertainty       string  `json:"uncertainty"`
}

type UsageMetricAvailability struct {
	MetricAvailabilityId string `json:"metric_availability_id"`
	MetricKey            string `json:"metric_key"`
	State                string `json:"state"`
	Reason               string `json:"reason"`
	CheckedAt            string `json:"checked_at"`
	Provenance           string `json:"provenance"`
}

type UsageAggregate struct {
	MetricKey    string  `json:"metric_key"`
	Value        float64 `json:"value"`
	Unit         string  `json:"unit"`
	ValueKind    string  `json:"value_kind"`
	SourceClass  string  `json:"source_class"`
	Scope        string  `json:"scope"`
	Aggregation  string  `json:"aggregation"`
	ProfileCount int64   `json:"profile_count"`
}

type UsageMetricAmbiguity struct {
	MetricKey string `json:"metric_key"`
	Reason    string `json:"reason"`
}

type UsageCandidate struct {
	ProfileId     string `json:"profile_id"`
	Alias         string `json:"alias"`
	Eligible      bool   `json:"eligible"`
	CapacityState string `json:"capacity_state"`
}

type UsageSnapshotResponse struct {
	SnapshotId    string                    `json:"snapshot_id"`
	ProfileId     string                    `json:"profile_id"`
	Alias         string                    `json:"alias"`
	Source        string                    `json:"source"`
	SourceVersion string                    `json:"source_version"`
	CapturedAt    string                    `json:"captured_at"`
	Status        string                    `json:"status"`
	TriggerReason string                    `json:"trigger_reason"`
	Observations  []UsageObservation        `json:"observations"`
	Availability  []UsageMetricAvailability `json:"availability"`
}

func (response UsageErrorResponse) Error() string { return response.Code }

type HTTPDoer interface {
	Do(*http.Request) (*http.Response, error)
}

type Client struct {
	baseURL    string
	httpClient HTTPDoer
}

func NewClient(baseURL string, httpClient HTTPDoer) *Client {
	return &Client{
		baseURL:    strings.TrimRight(baseURL, "/"),
		httpClient: httpClient,
	}
}

func (client *Client) ManageAnalyticsHistory(ctx context.Context, input HistoryRequest) (HistoryResponse, *http.Response, error) {
	var result HistoryResponse
	body, err := json.Marshal(input)
	if err != nil {
		return result, nil, err
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodPost, client.baseURL+HistoryPath, bytes.NewReader(body))
	if err != nil {
		return result, nil, err
	}
	request.Header.Set("Accept", "application/json")
	request.Header.Set("Content-Type", "application/json")
	httpClient := client.httpClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	response, err := httpClient.Do(request)
	if err != nil {
		return result, nil, err
	}
	defer response.Body.Close()
	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
		var failure UsageErrorResponse
		if err := json.NewDecoder(response.Body).Decode(&failure); err != nil {
			return result, response, err
		}
		return result, response, failure
	}
	err = json.NewDecoder(response.Body).Decode(&result)
	return result, response, err
}

func (client *Client) GetActivity(ctx context.Context, profileAlias, projectID string) (ActivityResponse, *http.Response, error) {
	var result ActivityResponse
	query := url.Values{}
	if profileAlias != "" {
		query.Set("profile", profileAlias)
	}
	if projectID != "" {
		query.Set("project", projectID)
	}
	path := ActivityPath
	if encoded := query.Encode(); encoded != "" {
		path += "?" + encoded
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, client.baseURL+path, nil)
	if err != nil {
		return result, nil, err
	}
	request.Header.Set("Accept", "application/json")
	httpClient := client.httpClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	response, err := httpClient.Do(request)
	if err != nil {
		return result, nil, err
	}
	defer response.Body.Close()
	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
		return result, response, fmt.Errorf("GET %s returned HTTP %d", ActivityPath, response.StatusCode)
	}
	if err := json.NewDecoder(response.Body).Decode(&result); err != nil {
		return result, response, err
	}
	return result, response, nil
}

func (client *Client) GetAnalytics(ctx context.Context, scope string) (AnalyticsResponse, *http.Response, error) {
	var result AnalyticsResponse
	path := AnalyticsPath
	if scope != "" {
		path += "?" + url.Values{"scope": []string{scope}}.Encode()
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, client.baseURL+path, nil)
	if err != nil {
		return result, nil, err
	}
	request.Header.Set("Accept", "application/json")
	httpClient := client.httpClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	response, err := httpClient.Do(request)
	if err != nil {
		return result, nil, err
	}
	defer response.Body.Close()
	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
		var failure UsageErrorResponse
		if err := json.NewDecoder(response.Body).Decode(&failure); err != nil {
			return result, response, fmt.Errorf("GET %s returned HTTP %d", AnalyticsPath, response.StatusCode)
		}
		return result, response, failure
	}
	if err := json.NewDecoder(response.Body).Decode(&result); err != nil {
		return result, response, err
	}
	return result, response, nil
}

func (client *Client) ExchangeBootstrap(ctx context.Context, input BootstrapRequest) (BootstrapResponse, *http.Response, error) {
	var result BootstrapResponse
	body, err := json.Marshal(input)
	if err != nil {
		return result, nil, err
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodPost, client.baseURL+BootstrapPath, bytes.NewReader(body))
	if err != nil {
		return result, nil, err
	}
	request.Header.Set("Accept", "application/json")
	request.Header.Set("Content-Type", "application/json")

	httpClient := client.httpClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	response, err := httpClient.Do(request)
	if err != nil {
		return result, nil, err
	}
	defer response.Body.Close()
	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
		return result, response, fmt.Errorf(
			"POST %s returned HTTP %d",
			BootstrapPath,
			response.StatusCode,
		)
	}
	if err := json.NewDecoder(response.Body).Decode(&result); err != nil {
		return result, response, err
	}
	return result, response, nil
}

func (client *Client) GetMetadata(ctx context.Context) (MetadataResponse, *http.Response, error) {
	var result MetadataResponse
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, client.baseURL+MetadataPath, nil)
	if err != nil {
		return result, nil, err
	}
	request.Header.Set("Accept", "application/json")

	httpClient := client.httpClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	response, err := httpClient.Do(request)
	if err != nil {
		return result, nil, err
	}
	defer response.Body.Close()
	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
		return result, response, fmt.Errorf(
			"GET %s returned HTTP %d",
			MetadataPath,
			response.StatusCode,
		)
	}
	if err := json.NewDecoder(response.Body).Decode(&result); err != nil {
		return result, response, err
	}
	return result, response, nil
}

func (client *Client) GetProjects(ctx context.Context) (ProjectsResponse, *http.Response, error) {
	var result ProjectsResponse
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, client.baseURL+ProjectsPath, nil)
	if err != nil {
		return result, nil, err
	}
	request.Header.Set("Accept", "application/json")
	httpClient := client.httpClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	response, err := httpClient.Do(request)
	if err != nil {
		return result, nil, err
	}
	defer response.Body.Close()
	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
		return result, response, fmt.Errorf("GET %s returned HTTP %d", ProjectsPath, response.StatusCode)
	}
	if err := json.NewDecoder(response.Body).Decode(&result); err != nil {
		return result, response, err
	}
	return result, response, nil
}

func (client *Client) GetSelection(ctx context.Context) (SelectionResponse, *http.Response, error) {
	var result SelectionResponse
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, client.baseURL+SelectionPath, nil)
	if err != nil {
		return result, nil, err
	}
	request.Header.Set("Accept", "application/json")
	httpClient := client.httpClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	response, err := httpClient.Do(request)
	if err != nil {
		return result, nil, err
	}
	defer response.Body.Close()
	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
		return result, response, fmt.Errorf("GET %s returned HTTP %d", SelectionPath, response.StatusCode)
	}
	if err := json.NewDecoder(response.Body).Decode(&result); err != nil {
		return result, response, err
	}
	return result, response, nil
}

func (client *Client) SetSelection(ctx context.Context, input SelectionRequest) (SelectionResponse, *http.Response, error) {
	var result SelectionResponse
	body, err := json.Marshal(input)
	if err != nil {
		return result, nil, err
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodPut, client.baseURL+SelectionPath, bytes.NewReader(body))
	if err != nil {
		return result, nil, err
	}
	request.Header.Set("Accept", "application/json")
	request.Header.Set("Content-Type", "application/json")
	httpClient := client.httpClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	response, err := httpClient.Do(request)
	if err != nil {
		return result, nil, err
	}
	defer response.Body.Close()
	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
		return result, response, fmt.Errorf("PUT %s returned HTTP %d", SelectionPath, response.StatusCode)
	}
	if err := json.NewDecoder(response.Body).Decode(&result); err != nil {
		return result, response, err
	}
	return result, response, nil
}

func (client *Client) RefreshUsage(ctx context.Context, input UsageRefreshRequest) (UsageSnapshotResponse, *http.Response, error) {
	var result UsageSnapshotResponse
	body, err := json.Marshal(input)
	if err != nil {
		return result, nil, err
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodPost, client.baseURL+UsageRefreshPath, bytes.NewReader(body))
	if err != nil {
		return result, nil, err
	}
	request.Header.Set("Accept", "application/json")
	request.Header.Set("Content-Type", "application/json")
	httpClient := client.httpClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	response, err := httpClient.Do(request)
	if err != nil {
		return result, nil, err
	}
	defer response.Body.Close()
	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
		var failure UsageErrorResponse
		if err := json.NewDecoder(response.Body).Decode(&failure); err != nil {
			return result, response, fmt.Errorf("POST %s returned HTTP %d", UsageRefreshPath, response.StatusCode)
		}
		return result, response, failure
	}
	if err := json.NewDecoder(response.Body).Decode(&result); err != nil {
		return result, response, err
	}
	return result, response, nil
}
func (client *Client) GetLatestUsage(ctx context.Context, alias string) (UsageSnapshotResponse, *http.Response, error) {
	var result UsageSnapshotResponse
	query := url.Values{"alias": []string{alias}}
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, client.baseURL+UsageLatestPath+"?"+query.Encode(), nil)
	if err != nil {
		return result, nil, err
	}
	request.Header.Set("Accept", "application/json")
	httpClient := client.httpClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	response, err := httpClient.Do(request)
	if err != nil {
		return result, nil, err
	}
	defer response.Body.Close()
	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
		var failure UsageErrorResponse
		if err := json.NewDecoder(response.Body).Decode(&failure); err != nil {
			return result, response, fmt.Errorf("GET %s returned HTTP %d", UsageLatestPath, response.StatusCode)
		}
		return result, response, failure
	}
	if err := json.NewDecoder(response.Body).Decode(&result); err != nil {
		return result, response, err
	}
	return result, response, nil
}
