// Code generated by codex-folio OpenAPI generator 1.0.0; DO NOT EDIT.
// Contract source: api/openapi.json
// Response schemas: BootstrapResponse, MetadataResponse, SelectionResponse, UsageSnapshotResponse
package httpapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
)

const (
	APIVersion           = "v1"
	ContractVersion      = "0.0.1-alpha"
	ContractSourceSHA256 = "c63f6969ad87f575511f210dbd365b6536ed887ecafdc09e569f28b956eb667a"
	BootstrapPath        = "/api/v1/bootstrap"
	MetadataPath         = "/api/v1/meta"
	SelectionPath        = "/api/v1/selection"
	UsageRefreshPath     = "/api/v1/usage/refresh"
)

type BootstrapRequest struct {
	BootstrapToken string `json:"bootstrap_token"`
}

type BootstrapResponse struct {
	CSRFToken string `json:"csrf_token"`
}

type MetadataResponse struct {
	APIVersion      string `json:"api_version"`
	ContractVersion string `json:"contract_version"`
	Product         string `json:"product"`
}

type SelectionRequest struct {
	Alias string `json:"alias"`
}

type SelectionResponse struct {
	ProfileId   string `json:"profile_id"`
	Alias       string `json:"alias"`
	DisplayName string `json:"display_name"`
	Warning     string `json:"warning"`
}

type UsageRefreshRequest struct {
	Alias string `json:"alias"`
}

type UsageErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type UsageObservation struct {
	ObservationId string  `json:"observation_id"`
	MetricKey     string  `json:"metric_key"`
	Value         float64 `json:"value"`
	Unit          string  `json:"unit"`
	ValueKind     string  `json:"value_kind"`
	SourceClass   string  `json:"source_class"`
	Scope         string  `json:"scope"`
	Aggregation   string  `json:"aggregation"`
	ObservedAt    string  `json:"observed_at"`
	WindowStart   string  `json:"window_start"`
	WindowEnd     string  `json:"window_end"`
	Provenance    string  `json:"provenance"`
	Freshness     string  `json:"freshness"`
	Availability  string  `json:"availability"`
}

type UsageMetricAvailability struct {
	MetricAvailabilityId string `json:"metric_availability_id"`
	MetricKey            string `json:"metric_key"`
	State                string `json:"state"`
	CheckedAt            string `json:"checked_at"`
	Provenance           string `json:"provenance"`
}

type UsageSnapshotResponse struct {
	SnapshotId    string                    `json:"snapshot_id"`
	ProfileId     string                    `json:"profile_id"`
	Alias         string                    `json:"alias"`
	Source        string                    `json:"source"`
	SourceVersion string                    `json:"source_version"`
	CapturedAt    string                    `json:"captured_at"`
	Observations  []UsageObservation        `json:"observations"`
	Availability  []UsageMetricAvailability `json:"availability"`
}

func (response UsageErrorResponse) Error() string { return response.Code }

type HTTPDoer interface {
	Do(*http.Request) (*http.Response, error)
}

type Client struct {
	baseURL    string
	httpClient HTTPDoer
}

func NewClient(baseURL string, httpClient HTTPDoer) *Client {
	return &Client{
		baseURL:    strings.TrimRight(baseURL, "/"),
		httpClient: httpClient,
	}
}

func (client *Client) ExchangeBootstrap(ctx context.Context, input BootstrapRequest) (BootstrapResponse, *http.Response, error) {
	var result BootstrapResponse
	body, err := json.Marshal(input)
	if err != nil {
		return result, nil, err
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodPost, client.baseURL+BootstrapPath, bytes.NewReader(body))
	if err != nil {
		return result, nil, err
	}
	request.Header.Set("Accept", "application/json")
	request.Header.Set("Content-Type", "application/json")

	httpClient := client.httpClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	response, err := httpClient.Do(request)
	if err != nil {
		return result, nil, err
	}
	defer response.Body.Close()
	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
		return result, response, fmt.Errorf(
			"POST %s returned HTTP %d",
			BootstrapPath,
			response.StatusCode,
		)
	}
	if err := json.NewDecoder(response.Body).Decode(&result); err != nil {
		return result, response, err
	}
	return result, response, nil
}

func (client *Client) GetMetadata(ctx context.Context) (MetadataResponse, *http.Response, error) {
	var result MetadataResponse
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, client.baseURL+MetadataPath, nil)
	if err != nil {
		return result, nil, err
	}
	request.Header.Set("Accept", "application/json")

	httpClient := client.httpClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	response, err := httpClient.Do(request)
	if err != nil {
		return result, nil, err
	}
	defer response.Body.Close()
	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
		return result, response, fmt.Errorf(
			"GET %s returned HTTP %d",
			MetadataPath,
			response.StatusCode,
		)
	}
	if err := json.NewDecoder(response.Body).Decode(&result); err != nil {
		return result, response, err
	}
	return result, response, nil
}

func (client *Client) GetSelection(ctx context.Context) (SelectionResponse, *http.Response, error) {
	var result SelectionResponse
	request, err := http.NewRequestWithContext(ctx, http.MethodGet, client.baseURL+SelectionPath, nil)
	if err != nil {
		return result, nil, err
	}
	request.Header.Set("Accept", "application/json")
	httpClient := client.httpClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	response, err := httpClient.Do(request)
	if err != nil {
		return result, nil, err
	}
	defer response.Body.Close()
	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
		return result, response, fmt.Errorf("GET %s returned HTTP %d", SelectionPath, response.StatusCode)
	}
	if err := json.NewDecoder(response.Body).Decode(&result); err != nil {
		return result, response, err
	}
	return result, response, nil
}

func (client *Client) SetSelection(ctx context.Context, input SelectionRequest) (SelectionResponse, *http.Response, error) {
	var result SelectionResponse
	body, err := json.Marshal(input)
	if err != nil {
		return result, nil, err
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodPut, client.baseURL+SelectionPath, bytes.NewReader(body))
	if err != nil {
		return result, nil, err
	}
	request.Header.Set("Accept", "application/json")
	request.Header.Set("Content-Type", "application/json")
	httpClient := client.httpClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	response, err := httpClient.Do(request)
	if err != nil {
		return result, nil, err
	}
	defer response.Body.Close()
	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
		return result, response, fmt.Errorf("PUT %s returned HTTP %d", SelectionPath, response.StatusCode)
	}
	if err := json.NewDecoder(response.Body).Decode(&result); err != nil {
		return result, response, err
	}
	return result, response, nil
}

func (client *Client) RefreshUsage(ctx context.Context, input UsageRefreshRequest) (UsageSnapshotResponse, *http.Response, error) {
	var result UsageSnapshotResponse
	body, err := json.Marshal(input)
	if err != nil {
		return result, nil, err
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodPost, client.baseURL+UsageRefreshPath, bytes.NewReader(body))
	if err != nil {
		return result, nil, err
	}
	request.Header.Set("Accept", "application/json")
	request.Header.Set("Content-Type", "application/json")
	httpClient := client.httpClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	response, err := httpClient.Do(request)
	if err != nil {
		return result, nil, err
	}
	defer response.Body.Close()
	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
		var failure UsageErrorResponse
		if err := json.NewDecoder(response.Body).Decode(&failure); err != nil {
			return result, response, fmt.Errorf("POST %s returned HTTP %d", UsageRefreshPath, response.StatusCode)
		}
		return result, response, failure
	}
	if err := json.NewDecoder(response.Body).Decode(&result); err != nil {
		return result, response, err
	}
	return result, response, nil
}
