// Shipped English copy; dates, numbers and time zones follow the OS locale.
export const copy = {
  product: "VenkataSudha CodexFolio",
  brand: "CodexFolio",
  selected: "Selected Profile",
  scope: "Dashboard Scope",
  combined: "Combined Identity View",
  none: "No Selected Profile",
  destinations: ["Overview", "Profiles", "Sessions", "Analytics", "Alerts", "Settings"],
  more: "More",
  skip: "Skip to content",
  local: "Local companion",
  title: "You can continue working",
  check: "Review capacity before continuing",
  empty: "Choose your first Identity Profile",
  emptyDetail:
    "Set up an Identity Profile in your terminal with codex-folio setup, then reopen the dashboard.",
  capacity: "Current capacity",
  alternatives: "Eligible alternatives",
  noAlternatives: "No eligible alternatives available.",
  eligible: "Authentication, home and installed Codex checks passed",
  ineligible: "Not eligible: check authentication, Identity Home and installed Codex.",
  recommended: "Recommended",
  withheld: "Refresh before choosing",
  noRecommendation: "No recommendation from current evidence.",
  refresh: "Refresh",
  refreshing: "Refreshing…",
  launch: "Launch Codex",
  handoff: "Prepare Handoff",
  details: "Open details",
  refreshStart: "Refreshing capacity. Last-known evidence remains visible with its original age.",
  refreshDone: "Capacity refreshed.",
  refreshFailed: "Refresh failed. Last-known values keep their original capture times.",
  selectedDone: "Selected Profile updated for future interactive launches.",
  combinedDetail: "Separate profile windows; quotas are not pooled. Selected Profile is unchanged.",
  running: "Your running Launch Profile is unchanged",
  runningDetail: "Changing scope cannot switch, stop or replace a running Codex process.",
  authorizing: "Authorizing local browser",
  relaunch: "Relaunch CodexFolio",
  expired:
    "This authorization is invalid, expired or already used. Open a fresh one-time link from your terminal.",
  missing: "Open a one-time dashboard link from your terminal.",
  unavailable:
    "The local service is unavailable. Start it again in your terminal and open the new dashboard link.",
  relaunchCommand: "codex-folio service start",
  authorizationDetail:
    "Existing foreground Codex work is unchanged. Persistent service installation is not required.",
  primary: "Primary window",
  secondary: "Secondary window",
  remaining: "remaining",
  lastKnown: "Last-known remaining",
  used: "used",
  resets: "Resets",
  window: "Provider window",
  unknownReset: "Reset unavailable",
  credits: "Credits",
  unsupportedCredits: "Unsupported by this source",
  captured: "Captured",
  source: "Source",
  provenance: "Provenance",
  availability: "Availability",
  metric: "Metric",
  value: "Value",
  assumptions: "Assumptions / uncertainty",
  recent: "Recent capacity",
  recentDetail:
    "Last twelve raw captures per profile; no sampling or gap filling. Solid: primary. Dashed: secondary.",
  noHistory: "No recent capacity captures.",
  traceTable:
    "Same captures as the chart; remaining percent. Dates and zone follow your OS locale.",
  sample: "Inspect capture",
  noValue: "Unavailable",
  conflicting: "Conflicting observations",
  stale: "Stale",
  ageUnknown: "Capture time unavailable",
  guidance: "Continue in your terminal",
  launchGuidance:
    "Run this from your project directory. Codex runs in the foreground; nothing has been launched by the dashboard.",
  handoffGuidance:
    "Use codex-folio checkpoint and codex-folio handoff in your project terminal to review and approve Safe Continuation. Nothing has been prepared or started here.",
  combinedGuidance: "Choose a single Identity Profile first.",
  close: "Close",
  later:
    "This dashboard journey is not available yet. Existing terminal commands remain available.",
  appearance: "Appearance",
  themes: ["System", "Light", "Dark"],
  locale: "Dates and numbers",
  osLocale: "Use operating-system locale",
  themeUnavailable: "Appearance changed for this tab; browser storage is unavailable.",
  secondsAgo: "seconds ago",
  minutesAgo: "minutes ago",
  hoursAgo: "hours ago",
  future: "Future capture; freshness unknown",
} as const;
export const stateCopy: Record<string, string> = {
  available: "Available",
  unsupported: "Unsupported",
  temporarily_unavailable: "Temporarily unavailable",
  stale: "Stale",
  partial: "Partial",
  contradictory: "Contradictory",
  reauthentication_required: "Reauthentication required",
  future_unknown: "Unknown source version",
  fresh: "Fresh",
  incompatible: "Incompatible evidence",
  ineligible: "Not eligible",
  source_missing: "Source missing",
  field_missing: "Field missing",
  capability_unsupported: "Unsupported capability",
  collection_failed: "Collection failed",
};
export const provenanceCopy: Record<string, string> = {
  "Provider-reported Metric": "Provider reported",
  "Locally-derived Metric": "Locally derived",
  "Estimated Metric": "Estimated",
  "Observed during session": "Observed during session",
};
