// Shipped English copy; dates, numbers and time zones follow the OS locale.
const number = new Intl.NumberFormat();

export const copy = {
  product: "VenkataSudha CodexFolio",
  brand: "CodexFolio",
  selected: "Selected Profile",
  scope: "Dashboard Scope",
  combined: "Combined Identity View",
  none: "No Selected Profile",
  destinations: ["Overview", "Profiles", "Sessions", "Analytics", "Alerts", "Settings"],
  more: "More",
  skip: "Skip to content",
  local: "Local companion",
  title: "You can continue working",
  check: "Review capacity before continuing",
  empty: "Choose your first Identity Profile",
  emptyDetail:
    "Set up an Identity Profile in your terminal with codex-folio setup, then reopen the dashboard.",
  capacity: "Current capacity",
  alternatives: "Eligible alternatives",
  noAlternatives: "No eligible alternatives available.",
  eligible: "Authentication, home and installed Codex checks passed",
  ineligible: "Not eligible: check authentication, Identity Home and installed Codex.",
  recommended: "Recommended",
  withheld: "Refresh before choosing",
  noRecommendation: "No recommendation from current evidence.",
  refresh: "Refresh",
  refreshing: "Refreshing…",
  launch: "Launch Codex",
  handoff: "Prepare Handoff",
  details: "Open details",
  refreshStart: "Refreshing capacity. Last-known evidence remains visible with its original age.",
  refreshDone: "Capacity refreshed.",
  refreshFailed: "Refresh failed. Last-known values keep their original capture times.",
  selectedDone: "Selected Profile updated for future interactive launches.",
  combinedDetail: "Separate profile windows; quotas are not pooled. Selected Profile is unchanged.",
  running: "Your running Launch Profile is unchanged",
  runningDetail: "Changing scope cannot switch, stop or replace a running Codex process.",
  authorizing: "Authorizing local browser",
  relaunch: "Relaunch CodexFolio",
  expired:
    "This authorization is invalid, expired or already used. Open a fresh one-time link from your terminal.",
  missing: "Open a one-time dashboard link from your terminal.",
  unavailable:
    "The local service is unavailable. Start it again in your terminal and open the new dashboard link.",
  relaunchCommand: "codex-folio service start",
  authorizationDetail:
    "Existing foreground Codex work is unchanged. Persistent service installation is not required.",
  primary: "Primary window",
  secondary: "Secondary window",
  remaining: "remaining",
  lastKnown: "Last-known remaining",
  used: "used",
  resets: "Resets",
  window: "Provider window",
  unknownReset: "Reset unavailable",
  credits: "Credits",
  unsupportedCredits: "Unsupported by this source",
  captured: "Captured",
  source: "Source",
  provenance: "Provenance",
  availability: "Availability",
  metric: "Metric",
  value: "Value",
  assumptions: "Assumptions / uncertainty",
  recent: "Recent capacity",
  recentDetail:
    "Last twelve raw captures per profile; no sampling or gap filling. Solid: primary. Dashed: secondary.",
  noHistory: "No recent capacity captures.",
  traceTable:
    "Same captures as the chart; remaining percent. Dates and zone follow your OS locale.",
  sample: "Inspect capture",
  noValue: "Unavailable",
  conflicting: "Conflicting observations",
  stale: "Stale",
  ageUnknown: "Capture time unavailable",
  guidance: "Continue in your terminal",
  handoffGuidance:
    "Use codex-folio checkpoint and codex-folio handoff in your project terminal to review and approve Safe Continuation. Nothing has been prepared or started here.",
  combinedGuidance: "Choose a single Identity Profile first.",
  close: "Close",
  later:
    "This dashboard journey is not available yet. Existing terminal commands remain available.",
  appearance: "Appearance",
  themes: ["System", "Light", "Dark"],
  locale: "Dates and numbers",
  osLocale: "Use operating-system locale",
  backgroundService: "Background service",
  enrollmentActive: "Installed and active",
  enrollmentInstalled: "Installed; start is pending",
  enrollmentNotInstalled: "On demand · Not enrolled",
  enrollmentUnavailable: "Native enrollment unavailable · On-demand access remains available",
  enrollmentMechanism: "Native per-user mechanism",
  enrollmentGuidance: "Review or change enrollment in your local terminal:",
  collectionSchedule: "Periodic collection schedule",
  collectionScheduleEnabled:
    "Enabled by explicit native service enrollment for this service session.",
  collectionScheduleDisabled:
    "On demand · Saved intervals do not enroll or start a persistent service.",
  collectionScheduleFloor: (minutes: number) =>
    `Provider-safe minimum · ${number.format(minutes)} minutes · Supported App Server read with no published polling cadence`,
  collectionActiveMinutes: "Managed Launch interval · minutes",
  collectionIdleMinutes: "Idle interval · minutes",
  collectionScheduleSave: "Save collection intervals",
  collectionScheduleSaving: "Saving periodic collection intervals.",
  collectionScheduleSaved: "Periodic collection intervals saved.",
  collectionScheduleFailed: "Periodic collection intervals were not changed.",
  analyticsRetention: "Analytics retention",
  analyticsRetentionDetail:
    "13 calendar months by default · Configurable from 30 days to unlimited · Scoped purge is reviewed separately.",
  manageAnalyticsData: "Manage analytics data",
  checkpointData: "Safe Continuation data",
  checkpointDataDetail:
    "Review retained checkpoints, set source-specific retention, export an approved checkpoint, or purge one checkpoint at a time.",
  themeUnavailable: "Appearance changed for this tab; browser storage is unavailable.",
  secondsAgo: "seconds ago",
  minutesAgo: "minutes ago",
  hoursAgo: "hours ago",
  future: "Future capture; freshness unknown",
} as const;

export const serviceHealthCopy = {
  lockedTitle: "Unlock for this user session",
  lockedState: "Settings · Vault locked · Explicit session unlock",
  lockedNotice:
    "The passphrase-backed service is locked after reboot. Sensitive collection is paused.",
  runTerminal: "In your local terminal, run",
  privatePrompt: "and follow the private prompt.",
  neverExpose:
    "Never place your passphrase in this dashboard, a saved command, an environment variable, or unattended startup configuration.",
  onDemand: "On-demand access does not require telemetry or persistent-service enrollment.",
  recoveryTitle: "Local data needs recovery",
  recoveryState: "Settings · Recovery required · No automatic deletion",
  recoveryNotice:
    "The service preserved the database and stopped writes. It will not silently reset your data.",
  recoveryGuidance: "Recovery guidance",
  recoverySteps: [
    "Keep the preserved database and recovery artifacts.",
    "Stop the service owner, then use the CLI recovery workflow to inspect health and available backups.",
    "Review an explicit recovery choice before restoring.",
  ],
  recoveryUnavailable:
    "Profiles, collection and continuation stay unavailable until the state owner reports recovery complete.",
  checkpointRecovery: "Checkpoint recovery",
  checkpointRetention: "Drafts and approved checkpoints retain their recorded revision and expiry.",
  checkpointBoundary:
    "Unknown source-process state cannot authorize a new launch. Verify the source terminal and choose a valid checkpoint after storage recovery.",
  vaultAndRecovery: "Vault and recovery",
  ready: "Unlocked for this service session · Database ready",
  locked: "Locked after reboot",
} as const;
export const stateCopy: Record<string, string> = {
  ready: "Ready",
  pending: "Pending",
  unavailable: "Unavailable",
  needs_reauthentication: "Reauthentication required",
  auto: "Automatic",
  browser: "Browser sign-in",
  "device-code": "Device code",
  reused: "Existing Codex sign-in",
  available: "Available",
  unsupported: "Unsupported",
  temporarily_unavailable: "Temporarily unavailable",
  stale: "Stale",
  partial: "Partial",
  contradictory: "Contradictory",
  reauthentication_required: "Reauthentication required",
  future_unknown: "Unknown source version",
  fresh: "Fresh",
  incompatible: "Incompatible evidence",
  ineligible: "Not eligible",
  source_missing: "Source missing",
  field_missing: "Field missing",
  capability_unsupported: "Unsupported capability",
  collection_failed: "Collection failed",
  local_metadata: "Local metadata",
};
export const provenanceCopy: Record<string, string> = {
  "Provider-reported Metric": "Provider reported",
  "Locally-derived Metric": "Locally derived",
  "Estimated Metric": "Estimated",
  "Observed during session": "Observed during session",
};

export const handoffCopy = {
  title: "Prepare Handoff",
  reviewTitle: "Review Safe Continuation",
  project: "Project",
  unknownSource: "Source profile unavailable",
  captured: "Repository-first draft captured · Nothing has started",
  saved: "Sanitized draft saved · Approval applies only to this revision",
  approved: "Approved · Terminal launch not started",
  checked: "Source and target readiness checked again",
  operationFailed: "Handoff action was rejected. Review the current revision and readiness.",
  prepared: "Approved · Terminal launch not started",
  starting: "Start reported · Waiting for foreground process",
  started: "Started · Running",
  exited: "Exited · Status",
  failed: "Failed · Codex did not start",
  readiness: "Handoff readiness",
  source: "Source process",
  sourceRunning:
    "Managed Launch is still running. Stop it in its terminal; CodexFolio will not kill it.",
  sourceUncertain:
    "Termination is uncertain. A missing exit report does not prove the source stopped.",
  sourceExited: "Definitively exited",
  target: "Target profile",
  targetReady: "Ready for current review",
  targetBlocked: "Not eligible; review authentication, Identity Home, and installed Codex support.",
  goal: "Goal",
  completed: "Completed work",
  pending: "Pending work",
  validation: "Known validation",
  risks: "Risks",
  next: "Next action",
  repositoryFirst: "Repository-first checkpoint",
  transcriptAssisted: "Transcript-assisted checkpoint",
  revision: "Revision",
  expires: "Expires",
  never: "Never",
  evidence: "Repository evidence and redaction",
  filesChanged: "files changed",
  branch: "Branch",
  head: "HEAD",
  unknown: "Unavailable",
  validationAge: "Validation age",
  notRecorded: "Not recorded",
  redactFiles: "Redact repository paths in the next revision",
  redactText: "Redact exact text (one value per line)",
  assistance: "Transcript assistance",
  assistanceDetail:
    "Off by default. For this handoff only, you may allow a bounded read of one Codex thread. Raw transcript, commands, credentials, arbitrary files, and Identity Homes never enter the dashboard.",
  assistanceConsent: "Allow transcript assistance for this handoff",
  assistanceConsentDetail:
    "Consent applies only to the thread ID below and is not remembered. No history is read until you request candidates.",
  threadId: "Codex thread ID",
  threadIdPlaceholder: "00000000-0000-0000-0000-000000000000",
  reviewCandidates: "Review transcript candidates",
  assistanceUnavailable:
    "Transcript assistance is unavailable. The repository-first draft remains unchanged.",
  candidatesReady:
    "Candidates are transient. Edit or redact them, then review the sanitized preview before approval.",
  reviewSanitized: "Review sanitized preview",
  sanitizedReady: "Sanitized preview ready. Approval below persists only this displayed revision.",
  approveSanitized: "Approve sanitized preview",
  cancelAssistance: "Cancel transcript assistance",
  assistanceCancelled: "Transcript assistance cancelled · Repository-first draft restored",
  save: "Save sanitized draft",
  approve: "Approve this revision",
  checkAgain: "Check readiness again",
  cancel: "Cancel",
  terminal: "Continue in your terminal",
  terminalDetail:
    "Run this service-validated handoff command to start fresh installed Codex in the foreground with normal input, output, signals, and exit status.",
  approvalDetail:
    "Approval is revision-bound. Source stop, target eligibility, expiry, current repository access, and revision are checked again before launch.",
  boundary:
    "Starts a fresh foreground Codex session in the same working directory. No thread is resumed or copied, and no arbitrary browser command is accepted.",
} as const;

export const checkpointCopy = {
  title: "Safe Continuation data",
  detail:
    "Checkpoint content stays encrypted at rest. Browser rows expose only safe project labels, state, source, revision, and retention dates.",
  loading: "Loading checkpoint inventory…",
  loaded: "Checkpoint inventory loaded.",
  empty: "No retained checkpoints.",
  repositoryRetention: "Repository-first retention",
  assistedRetention: "Transcript-assisted retention",
  retentionHint: "Use 1 or more whole days, or unlimited.",
  saveRetention: "Save retention",
  retentionSaved: "Retention policy saved.",
  retentionFailed: "Retention or checkpoint action was rejected.",
  status: "State",
  source: "Source",
  created: "Created",
  expires: "Expires",
  revision: "Revision",
  export: "Export",
  encrypted: "Encrypted .cfolio",
  plaintext: "Plaintext JSON",
  passphrase: "Export passphrase",
  plaintextWarning:
    "I understand plaintext is not encrypted and may be readable by other software or people with access to the downloaded file.",
  previewExport: "Preview export",
  downloadExport: "Download export",
  cancelExport: "Cancel export",
  included: "Included",
  excluded: "Always excluded",
  exportReady: "Export preview ready. No file has been created.",
  downloadReady: "Download prepared. Your browser controls the destination and overwrite behavior.",
  purge: "Purge checkpoint",
  previewPurge: "Preview purge",
  purgeWarning:
    "This removes this exact checkpoint revision after confirmation. It never stops Codex.",
  purgeConfirmation: "Type PURGE to confirm",
  applyPurge: "Purge exact revision",
  cancelPurge: "Cancel purge",
  purgeReady: "Purge preview ready. Nothing has been removed.",
  purged: "Checkpoint purged.",
  never: "Never",
  unavailable: "Unavailable",
  refresh: "Refresh inventory",
} as const;

export const checkpointStateCopy: Record<string, string> = {
  retained: "Retained",
  recoverable: "Recoverable",
  completed: "Completed",
  expired: "Expired",
  "start uncertain": "Start uncertain",
};

export const checkpointSourceCopy: Record<string, string> = {
  "repository-first": "Repository-first",
  "transcript-assisted": "Transcript-assisted",
};

export const checkpointExportFieldCopy: Record<string, string> = {
  format_version: "Format version",
  exported_at: "Exported at",
  checkpoint: "Checkpoint",
  project_alias: "Project alias",
  project_basename: "Project basename",
  approved_fields: "Six approved fields",
  repository_metadata: "Repository metadata",
  revision: "Revision",
  expiry: "Expiry",
  credentials: "Credentials",
  identity_homes: "Identity Homes",
  canonical_repository_paths: "Canonical repository paths",
  raw_transcripts: "Raw transcripts",
  raw_diffs: "Raw diffs",
  commands_and_tool_output: "Commands and tool output",
  analytics: "Analytics",
  configuration: "Configuration",
};

export const analyticsCopy = {
  title: "Analytics",
  subtitle: "Capacity · Historical bucket zone stays attached to every record",
  compareTitle: "Compare capacity",
  compareSubtitle: "Compatible evidence only",
  sections: "Analytics sections",
  tabs: ["Capacity", "Tokens", "Projects", "Models", "Activity", "Compare"],
  comingLater: "Available in a later analytics slice",
  project: "Project",
  allProjects: "All projects",
  tokensTitle: "Token observations",
  tokensSubtitle:
    "Observed-session token metadata only. Values keep their record, project, source and provenance.",
  projectsTitle: "Projects",
  projectsSubtitle:
    "App-local Project Aliases and basenames. Canonical repository paths stay private.",
  modelsTitle: "Models",
  modelsSubtitle:
    "Models observed in supported local session metadata; this is not provider capability or task-suitability data.",
  activityTitle: "Activity",
  activitySubtitle:
    "Managed Launches and Observed Sessions remain distinct. Correlation never implies causation.",
  noTokens: "Token metrics are unsupported for the records matching these filters.",
  noProjects: "No Project Identity matches these filters.",
  noModels: "Model metadata is unsupported for the records matching these filters.",
  noActivity: "No Managed Launch or Observed Session matches these filters.",
  observedRecords: (count: number) =>
    `${count} matching ${count === 1 ? "record" : "records"} from normalized activity history.`,
  tokensChart:
    "Token observations by activity record. Exact values and evidence are in the following table.",
  projectsChart:
    "Activity records by Project Identity. Exact counts and identity metadata are in the following table.",
  modelsChart:
    "Activity records by observed model. Exact counts and evidence are in the following table.",
  chartTableNote: "Bars summarize the same rows as the following accessible table.",
  record: "Record",
  tokens: "Tokens",
  model: "Model",
  records: "Records",
  lastObserved: "Last observed",
  recordType: "Record type",
  lifecycle: "Lifecycle",
  correlation: "Correlation",
  evidence: "Evidence",
  unsupported: "Unsupported",
  editAlias: "Edit Project Alias",
  alias: "Project Alias",
  basename: "Basename",
  saveAlias: "Save Alias",
  cancelAlias: "Cancel",
  aliasSaved:
    "Project Alias updated. Historical records now use the current app-local alias in this view.",
  aliasFailed: "Project Alias could not be updated.",
  activityLoading: "Loading normalized activity history.",
  activityLoaded: (count: number) =>
    `${count} normalized activity ${count === 1 ? "record" : "records"} loaded.`,
  activityRetained: (count: number) =>
    `${count} previously loaded activity ${count === 1 ? "record" : "records"} retained.`,
  activityLoadFailed:
    "Normalized activity history could not be refreshed. Previously loaded records are retained.",
  projectsLoading: "Loading Project Identities.",
  projectsLoaded: (count: number) =>
    `${count} Project ${count === 1 ? "Identity" : "Identities"} loaded.`,
  projectsLoadFailed:
    "Project Identities could not be refreshed. Previously loaded identities are retained.",
  projectsInitialLoadFailed:
    "Project Identities could not be loaded. No Project Identity result is available.",
  projectPrivacy:
    "Ordinary analytics use the current Project Alias or basename. Canonical paths are not returned to the browser.",
  sourceEvidence: (source: string, version: string, provenance: string) =>
    `${source}${version ? ` ${version}` : ""} · ${provenance}`,
  observedSession: "Observed Session",
  managedLaunch: "Managed Launch",
  scope: "Analytics scope",
  history: "History range",
  window: "Capacity window",
  last30Days: "Last 30 days",
  last90Days: "Last 90 days",
  last13Months: "Last 13 months",
  allHistory: "All retained history",
  bothWindows: "Both provider windows",
  primary: "Primary window",
  secondary: "Secondary window",
  primaryShort: "primary",
  secondaryShort: "secondary",
  current: "Current capacity",
  capacityHistory: "Capacity history",
  bucketZone: "Monthly selection zone: UTC",
  loading: "Loading stored capacity history.",
  loaded: (count: number) =>
    `${count} compatible stored aggregate ${count === 1 ? "record" : "records"} loaded.`,
  loadFailed: "Stored capacity history is unavailable. Current capacity remains visible.",
  monthlyFinal: (count: number) => `${count} monthly final ${count === 1 ? "sample" : "samples"}`,
  chartLabel:
    "Monthly final capacity samples. Solid primary-window and dashed secondary-window series; exact values and gaps are in the following table.",
  chartLegend:
    "Solid: primary-window remaining · Dashed: secondary-window remaining · A break means no compatible stored sample.",
  historyCaption:
    "The same monthly final samples as the chart. Percentages are never summed; provider windows and source remain attached.",
  month: "Captured month (UTC)",
  primaryRemaining: "Primary remaining",
  secondaryRemaining: "Secondary remaining",
  availability: "Availability",
  source: "Source / provenance",
  providerWindow: "Provider window",
  providerWindows: "Provider windows",
  observed: (value: string) => `Observed ${value}`,
  captured: (value: string) => `Captured ${value}`,
  windowDetail: (value: string) => `Window ${value}`,
  assumptions: (value: string) => `Assumptions ${value}`,
  uncertainty: (value: string) => `Uncertainty ${value}`,
  lastKnown: "Last-known",
  noCompatibleSample: "No compatible sample",
  noHistory: "No compatible stored capacity history matches these filters.",
  unavailable: "Unavailable",
  future: "Future capture; freshness unknown",
  secondsAgo: (value: string) => `${value} seconds ago`,
  minutesAgo: (value: string) => `${value} minutes ago`,
  hoursAgo: (value: string) => `${value} hours ago`,
  combined: "Combined Identity View",
  explicit: "Explicit comparison",
  selectionRemains: (alias: string) => `Selected Profile remains ${alias}`,
  none: "No Selected Profile",
  compareCaption: "Subscription capacity · Per-profile limits, never one pooled percentage",
  profile: "Profile",
  evidenceState: "Evidence age / state",
  apiCredit: "API credit and spend",
  noApiCredit: "Unavailable from the current supported source.",
  unitBoundary: "Currency and API units stay separate from subscription capacity percentages.",
  profiles: (count: number) => `${count} ${count === 1 ? "profile" : "profiles"}`,
  deduplication:
    "Shared login/workspace evidence is deduplicated by the analytics service before compatible absolute metrics are combined. Per-profile subscription percentages are never combined.",
  resetUnavailable: "Reset unavailable",
  boundary:
    "Each provider window keeps its stored boundaries, timezone, unit, source version and provenance. Monthly final selection never sums percentages or fills gaps.",
  displayZone: (value: string) =>
    `Dates display in your operating-system locale and ${value}; stored bucket zones are unchanged.`,
  localData: "Local analytics data",
  localDataDetail:
    "Preview normalized exports, configure bounded retention, or review an explicit scoped purge.",
  previewAnalyticsExport: "Preview analytics export",
  manageRetention: "Manage retention",
  previewScopedPurge: "Preview scoped purge",
} as const;

export const analyticsDataCopy = {
  exportTitle: "Preview before anything leaves",
  exportSubtitle: "Analytics · Normalized JSON or CSV",
  separation:
    "Analytics export is separate from portable configuration, diagnostics, and encrypted continuation checkpoints. Each has its own explicit scope.",
  format: "Export format",
  datasets: "Datasets",
  dataset: "Dataset",
  datasetLabels: {
    usage: "Usage",
    availability: "Availability",
    aggregates: "Aggregates",
    activity: "Activity",
  },
  usage: "Usage",
  aggregates: "Aggregates",
  observedSessions: "Observed Sessions",
  managedLaunches: "Managed Launches",
  checkpoints: "Checkpoints",
  includePaths: "Include canonical project paths explicitly",
  pathBoundary:
    "Default: Project Aliases and basenames only. Identity Home paths, credentials, raw provider payloads, conversation or tool content, commands, diffs, diagnostics, and vault material are never analytics export fields.",
  exportScope: (from: string) =>
    `The current Analytics profile, project, and retained range are used. Start: ${from}. End: all retained history.`,
  exportLoading: "Preparing an exact normalized export preview.",
  exportReady: "Export preview ready. Download uses these exact retained records.",
  exportFailed: "Export preview failed. No download was created.",
  downloadStarted: "Browser download started from the reviewed preview.",
  previewCaption: "Analytics export preview",
  previewSummary: (dataset: string, count: number) =>
    `${dataset} · ${number.format(count)} ${count === 1 ? "record" : "records"}`,
  fields: "Included fields",
  records: "Records",
  excluded:
    "Excluded content remains excluded even when canonical project paths are explicitly included. The browser chooses the download destination; CodexFolio does not upload or overwrite one.",
  previewExport: "Preview export",
  download: (format: string) => `Download ${format.toUpperCase()}`,
  cancelExport: "Cancel export",
  retentionTitle: "Analytics retention",
  retentionSubtitle: "Local normalized history · Independent from diagnostics and checkpoints",
  retentionLoading: "Loading the current analytics retention setting.",
  retentionSaving: "Saving analytics retention.",
  retentionFailed: "Analytics retention could not be updated. Existing data remains available.",
  retentionSaved: "Analytics retention saved. Existing data was not processed.",
  retentionMaintained: (processed: number, more: boolean) =>
    `Analytics retention saved. ${number.format(processed)} records processed in this bounded run.${more ? " More eligible records remain for a later run." : " No additional bounded batch was reported."}`,
  currentSetting: "Current setting:",
  retentionSetting: "Retention setting",
  retentionDays: "Retention days",
  thirteenMonths: "13 calendar months",
  unlimited: "Unlimited",
  days: (value: string) => `${value} days`,
  customDays: "Custom days (minimum 30)",
  loading: "Loading…",
  runMaintenance: "Run one bounded maintenance batch after saving",
  retentionBoundary:
    "Retention compacts eligible detail in bounded transactions. Aggregates keep normalized facts until explicit purge; provider windows, bucket zones, current state, and running or referenced activity keep their existing semantics. This does not enroll a scheduler.",
  saveRetention: "Save retention",
  back: "Back to Analytics",
  purgeTitle: "Preview scoped purge",
  purgeSubtitle: "Dry run first · Every scope dimension is explicit",
  purgeIsolation:
    "Analytics, activity, and checkpoint deletion is independent of Identity Profiles, Identity Homes, authentication, configuration packs, vault keys, and quarantine.",
  purgeProfile: "Purge profile",
  purgeProject: "Purge project",
  allProfiles: "All profiles",
  allProjects: "All projects",
  noProject: "No Project Identity",
  from: "From",
  to: "To",
  allHistory: "All retained history",
  chooseDate: "Choose date and time",
  fromDate: "From date and time",
  toDate: "To date and time",
  recordClasses: "Record classes",
  purgeDates:
    "From is inclusive and To is exclusive. Aggregate buckets and activity intervals must fit wholly inside the range. Checkpoints require All profiles.",
  purgeLoading: "Counting the exact scoped records without deleting anything.",
  purgeReady: "Purge preview ready. Review every count and type the scope-bound confirmation.",
  purgeFailed: "Purge preview failed. Existing data remains unchanged.",
  purgeApplying: "Applying the confirmed scoped purge.",
  purgeApplied: "Scoped analytics data purged.",
  purgeStale: "The confirmation is invalid or stale. Nothing was deleted; preview the scope again.",
  purgeCaption: "Scoped purge dry-run counts",
  recordClass: "Record class",
  purgeLimit: (limit: number, executable: boolean) =>
    `${executable ? "This scope can be applied" : "This scope is too large to apply"}. Atomic limit: ${number.format(limit)} affected records.`,
  confirmation: "Scope-bound confirmation",
  previewPurge: "Preview purge",
  applyPurge: "Apply scoped purge",
} as const;

export const profileCopy = {
  title: "Profiles",
  localOnly: "Local identity operations leave remote identities, billing and quota unchanged.",
  add: "Add Identity Profile",
  inventory: "Profile inventory · Safe local metadata",
  displayName: "Display Name",
  alias: "CLI Alias",
  loginIdentity: "Login Identity",
  workspace: "Workspace",
  authentication: "Authentication",
  identityHome: "Identity Home",
  configuration: "Configuration",
  manageConfiguration: "Manage Shared Configuration",
  lastRefresh: "Last successful refresh",
  never: "Never",
  noPack: "None",
  pending: "Pending · Resume setup",
  selected: "Ready · Selected",
  selectedMessage: "Selected Profile updated for future interactive launches.",
  selectionFailed: "Selected Profile could not be updated.",
  select: "Select",
  edit: "Edit",
  reauthenticate: "Reauthenticate",
  launch: "Launch Codex",
  launchGuidance: "Run this in your project terminal; the dashboard has not launched Codex:",
  removal: "Removal and recovery",
  reviewRemoval: "Review local removal",
  remoteUnaffected: "Profiles · This never deletes a remote OpenAI identity",
  removalWarning:
    "Running Managed Launches block removal. Choose a replacement if removing Selected Profile.",
  confirmAlias: "Type CLI Alias to confirm",
  confirmAliasHelp: "The value must match the exact CLI Alias, including letter case.",
  replacement: "Replacement Selected Profile",
  chooseReplacement: "Choose a valid replacement",
  confirmRemoval: "Confirm local removal",
  managedRemoval: "Managed home: seven-day quarantine.",
  referencedRemoval: "Referenced home: unregister only; external files stay in place.",
  managedRemovalDetail:
    "Managed Identity Home: seven-day quarantine, then explicit purge. Restore within quarantine to recover the profile.",
  referencedRemovalDetail:
    "Referenced Identity Home: unregister only. External files are never quarantined, deleted or rewritten.",
  recovery: "Managed Identity Home recovery",
  recoverableUntil: "Recoverable until",
  restore: "Restore",
  purge: "Purge permanently",
  reviewPurge: "Review final local purge",
  purgeWarning:
    "Final purge permanently removes this quarantined local profile and its Managed Identity Home.",
  confirmPurge: "Confirm final purge",
  quarantinedMessage: "Identity Profile moved to seven-day local quarantine.",
  deregisteredMessage:
    "Local registration removed. The Referenced Identity Home and remote OpenAI identity are unchanged.",
  restoredMessage: "Identity Profile restored from local quarantine.",
  purgedMessage: "Quarantined local profile permanently purged.",
  removalBlocked: "Removal is blocked while this Identity Profile has a running Managed Launch.",
  replacementRequired: "Choose a different Ready Identity Profile as the replacement selection.",
  confirmationInvalid: "Type the exact CLI Alias to confirm this local action.",
  quarantineInvalid: "This local quarantine action is no longer available. Refresh Profiles.",
  quarantineExpired: "The restoration window has expired. Review final purge instead.",
  managed: "Managed",
  referenced: "Referenced",
  reusedHome: "Reused for reauthentication",
  save: "Save changes",
  cancel: "Cancel",
  finish: "Finish setting up",
  setupPending: "Pending Profile · Not selectable or launchable yet",
  setupGuidance: "Choose the local Identity Home, then continue authentication with Codex.",
  reauthTitle: "Reauthenticate",
  reauthPending: "Not eligible until authentication is usable",
  reauthGuidance: "Codex authentication will be checked before any sign-in starts.",
  identity: "Identity",
  setupProgress: "Setup progress",
  authenticate: "Authenticate",
  ready: "Ready",
  managedOption: "Managed Identity Home (default)",
  referencedOption: "Reference an existing Identity Home",
  referencedPath: "Existing Identity Home path",
  codexOverride: "Installed Codex override (optional)",
  codexOverrideHelp: "Leave blank to use the installed Codex discovered on PATH.",
  authenticateWithCodex: "Authenticate with installed Codex",
  credentialsStay: "Credentials stay with Codex. CodexFolio does not collect your password.",
  browser: "Browser sign-in",
  device: "Device code",
  continue: "Continue in Codex",
  saveClose: "Save and close",
  setupStatus: "Setup status",
  installedCodex: "Installed Codex",
  found: "Found",
  checkedOnStart: "Checked when setup starts",
  validated: "Validated",
  waiting: "Waiting",
  optionalPack: "Optional · Set in Profiles",
  setupSaved: "Setup is saved. Resume here after signing in.",
  reauthSaved: "The established Identity Home stays unchanged.",
  terminalRequired: "Continue device-code authentication in your terminal:",
  back: "Back to Profiles",
  updated: "Identity Profile metadata updated.",
  readyMessage: "Identity Profile is ready.",
  pendingMessage: "Pending Profile saved for resume.",
  failed: "Profile action failed.",
  invalid: "Check the profile details and try again.",
  aliasTaken: "That CLI Alias is already registered.",
  notSelectable: "This Identity Profile is not ready to select.",
  authenticationFailed: "Codex authentication did not complete.",
  authenticationCancelled: "Codex authentication was cancelled.",
  authenticationUnavailable: "Codex authentication is unavailable.",
  homeInvalid: "Choose a valid Identity Home.",
  validationFailed: "Codex could not validate this Identity Profile.",
  duplicateWarning:
    "Codex-reported Login Identity or Workspace may already be registered; this local profile remains distinct.",
  warning: "Profile setup completed with a warning.",
  unknown: "Not provided",
} as const;

export const profileErrorCopy: Record<string, string> = {
  CF_PROFILE_SETUP_INVALID: profileCopy.invalid,
  CF_PROFILE_ALIAS_INVALID: profileCopy.invalid,
  CF_PROFILE_ALIAS_TAKEN: profileCopy.aliasTaken,
  CF_PROFILE_NOT_SELECTABLE: profileCopy.notSelectable,
  CF_PROFILE_AUTHENTICATION_FAILED: profileCopy.authenticationFailed,
  CF_PROFILE_AUTHENTICATION_CANCELLED: profileCopy.authenticationCancelled,
  CF_PROFILE_AUTHENTICATION_UNAVAILABLE: profileCopy.authenticationUnavailable,
  CF_PROFILE_HOME_INVALID: profileCopy.homeInvalid,
  CF_PROFILE_VALIDATION_FAILED: profileCopy.validationFailed,
  CF_PROFILE_REMOVAL_BLOCKED: profileCopy.removalBlocked,
  CF_PROFILE_REPLACEMENT_REQUIRED: profileCopy.replacementRequired,
  CF_PROFILE_CONFIRMATION_INVALID: profileCopy.confirmationInvalid,
  CF_PROFILE_QUARANTINE_INVALID: profileCopy.quarantineInvalid,
  CF_PROFILE_QUARANTINE_EXPIRED: profileCopy.quarantineExpired,
};

export const configurationCopy = {
  title: "Shared Configuration Packs",
  localOnly:
    "Reviewed declarative configuration only. Credentials and Identity Home content stay excluded.",
  back: "Back to Profiles",
  assignment: "Profile assignment",
  noneAssigned: "No Shared Configuration Pack assigned",
  approvedVersion: "Approved pack version",
  chooseVersion: "Choose an approved version",
  assign: "Assign reviewed version",
  managedOnly: "Projection is available only for a Ready Profile with a Managed Identity Home.",
  projection: "Projection preview",
  projectionDetail:
    "Review every target path and preserved local conflict before applying. Applying never overwrites a preserved local change.",
  preview: "Preview projection",
  projectionReview: "Review projection",
  noConflicts: "No profile-local conflicts detected.",
  conflictsPreserved: "These profile-local files will be preserved:",
  apply: "Apply reviewed projection",
  promotion: "Reviewed promotion",
  promotionDetail:
    "Promotion creates a new immutable approved version from profile-local overrides. It never reverse-synchronizes automatically or changes the current assignment.",
  newVersion: "New pack version",
  previewPromotion: "Preview promotion",
  promotionReview: "Review new immutable version",
  noLocalChanges: "No profile-local changes are present in this promotion.",
  promotionWarning: "The new version contains these reviewed changes:",
  promote: "Create reviewed version",
  create: "Create a declarative draft",
  createDetail:
    "Choose only the fixed configuration documents below. Browser requests cannot name arbitrary paths or read files from an Identity Home.",
  packID: "Pack ID",
  version: "Version",
  configDocument: "config.toml (optional)",
  agentsDocument: "AGENTS.md (optional)",
  pluginsDocument: "plugins.lock (optional)",
  saveDraft: "Save draft",
  versions: "Version health",
  noVersions: "No Shared Configuration Pack versions yet.",
  approve: "Approve reviewed draft",
  draftCount: "{count} draft version(s) await explicit review.",
  digest: "Content digest:",
  cancel: "Cancel",
  draftCreated: "Declarative draft saved. It is not approved or assigned.",
  approved: "Reviewed pack version approved.",
  assigned: "Reviewed pack version assigned. Projection has not been applied.",
  previewReady: "Projection preview ready. Review it before applying.",
  applied: "Reviewed projection applied; profile-local conflicts were preserved.",
  promotionReady: "Promotion preview ready. Review it before creating the version.",
  promoted: "Reviewed immutable pack version created. The profile assignment is unchanged.",
  failed: "Shared Configuration Pack action failed.",
  invalid: "Review the declarative configuration and current version, then try again.",
  notApproved: "Only an approved pack version can be assigned.",
  reviewRequired: "Review the preview again before applying or promoting.",
  projectionFailed: "Projection was not applied. Local configuration remains preserved.",
} as const;

export const configurationErrorCopy: Record<string, string> = {
  CF_CONFIGPACK_INVALID: configurationCopy.invalid,
  CF_CONFIGPACK_NOT_APPROVED: configurationCopy.notApproved,
  CF_CONFIGPACK_PROMOTION_REVIEW_REQUIRED: configurationCopy.reviewRequired,
  CF_CONFIGPACK_PROJECTION_FAILED: configurationCopy.projectionFailed,
};

export const launchCopy = {
  title: "Launch prepared in your terminal",
  detail: "Foreground Codex · Installed Codex owns the session",
  prepared: "Prepared · Not started",
  waiting: "Prepared · Waiting for process start",
  running: "Started · Running",
  exited: "Exited",
  exitStatus: "Status",
  failed: "Failed · Codex did not start",
  unchanged: "Your running Launch Profile is unchanged",
  unchangedDetail: "Changing Selected Profile cannot switch, stop or replace this process.",
  profile: "Launch Profile",
  project: "Project",
  noProjects: "No Project Identity is registered",
  workingDirectory: "Working directory",
  notSelected: "Select a Project Identity",
  arguments: "Arguments",
  argumentsDetail: "Append installed Codex arguments after the final --",
  terminal: "Continue in your terminal",
  terminalDetail:
    "Run the command below. The service validates the Launch Plan; Codex then uses this terminal's input, output and signals.",
  registerProject: "Register the current repository in your terminal first:",
  lifecycleDetail:
    "The dashboard reports Started only after the CLI reports the actual process start. A nonzero exit remains an exit status; it is not treated as quota exhaustion by itself.",
  boundary:
    "The browser cannot run arbitrary commands, expose Identity Home paths, detach Codex or replace its terminal.",
  back: "Back",
} as const;

export const sessionsCopy = {
  locallyDerived: "Locally derived",
  title: "Sessions",
  subtitle: "Managed Launches and Observed Sessions retain separate boundaries.",
  metadata: "Metadata only. No prompts, responses, commands or diffs.",
  filterNote: "Timeline filters do not change Selected Profile or a running Launch Profile.",
  profile: "Profile",
  project: "Project",
  dates: "Date range",
  type: "Record type",
  allProfiles: "All profiles",
  allProjects: "All projects",
  allTypes: "All record types",
  allDates: "All dates",
  week: "Last 7 days",
  month: "Last 30 days",
  custom: "Custom dates",
  from: "From date",
  to: "Through date",
  dateNote:
    "Dates filter launch record creation or observed start times in your display zone; both dates are inclusive.",
  invalidDates: "Choose a through date on or after the from date.",
  timeline: "Metadata timeline",
  zone: "Display zone",
  time: "Time",
  observedStarted: "Started",
  launchRecorded: "Launch recorded",
  abandonedAt: "Abandoned at",
  state: "State",
  action: "Action",
  details: "Open details",
  back: "Back to Sessions",
  managed: "Managed Launch",
  observed: "Observed Session",
  launchDetails: "Launch details",
  observedDetails: "Observed details",
  launchProfile: "Launch Profile (immutable)",
  ended: "Ended",
  lastSeen: "Last observed",
  noEnd: "No exit boundary recorded",
  observedBoundary:
    "Last observed is a source metadata timestamp, not a process exit or a live heartbeat.",
  managedBoundary:
    "Launch recorded is preparation time. Running confirms process start; Abandoned does not prove a normal exit. Observed facts remain separate.",
  evidence: "Evidence",
  source: "Source",
  version: "Source version",
  provenance: "Provenance",
  correlation: "Correlation",
  confidence: "Correlation confidence",
  evidenceType: "Correlation evidence",
  correlationNote:
    "Correlation is not causation. Time proximity and matching display text do not establish a relationship.",
  related: "Related records",
  noRelated: "No supported relationship to another record is established.",
  missingRelated: "The related record is unavailable in the retained timeline.",
  id: "Record ID",
  sourceId: "Source session ID",
  basename: "Project basename",
  model: "Model",
  tokens: "Tokens",
  exit: "Exit status",
  unavailable: "Unavailable",
  partial: "Partial metadata",
  available: "Recorded metadata available",
  availability: "Availability",
  freshness: "Freshness",
  recorded: "Recorded history; current source freshness is unknown",
  noMetrics: "Token and model observations are unavailable from this Managed Launch record.",
  noRecords: "No records match these filters. Missing history does not mean zero activity.",
  loading: "Loading recorded timeline…",
  reload: "Reload timeline",
  loaded: "Timeline read at",
  reloadNote: "Reload reads retained service metadata; it does not collect new Codex activity.",
  failed: "Timeline unavailable. Try reloading the retained service metadata.",
  retained: "Reload failed. Showing the previous timeline with its original record timestamps.",
  count: "{count} matching records",
  page: "Page {page} of {pages}",
  previous: "Previous page",
  next: "Next page",
} as const;

export const sessionStateCopy: Record<string, string> = {
  managed_launch: sessionsCopy.managed,
  observed_session: sessionsCopy.observed,
  running: "Running",
  pending: "Pending",
  exited: "Exited",
  abandoned: "Abandoned",
  uncorrelated: "Uncorrelated",
  correlated: "Correlated",
  ambiguous: "Ambiguous",
  contradictory: "Contradictory",
  high: "High",
  explicit: "Explicit source session ID",
  codex_folio: "CodexFolio",
  local_metadata: "Supported local metadata",
};
